#!/bin/bash

for ((G=0; G<=27; G++)); do
    /home/cber/Desktop/dsi-studio/dsi_studio --action=cnt --source=Connectometry\ Databases/PDAM0.rd.db.fib.gz --demo=Connectometry\ Databases/PDAM_DemografGeral.csv --variable_list=0,1,3,4,$G --t_threshold=2 --length_threshold=20 --no_tractogram=0 --exclude_cb=1 --permutation=4000 --voi=$G > log$G.txt
done
